version: '3'
services:

  disque:
    image: blacksquaremedia/disque:1.0-rc1

  debug-seed:
    build: ./debug-seed
    command: bundle exec ruby seed.rb
    environment:
      - DISQUE_ADDRS=disque:7711
    depends_on:
      - disque

  disque-web:
    build: .
    command: bundle exec rackup --host=0.0.0.0 --port=9292
    environment:
      - DISQUE_ADDRS=disque:7711
    ports:
      - 127.0.0.1:9292:9292
    depends_on:
      - debug-seed
